### ISSUE TITLE
cast to void produces wrong code

### ISSUE THREAD

**Issue by TotallyGamerJet** [gotranspile/cxgo#13]
the following c code:
```
int a = 0;
(void)a;
```
should produce:
```
var a int = 0
_ = a
```
instead, it produces:
```
var a int = 0
a 
```
which doesn't compile in go because the variable is evaluated but not used

**Comment by dennwc** [comment]
There's a [test case](https://github.com/gotranspile/cxgo/blob/b05e34239f83277e75cb9047052e984a1d25ea68/parse_test.go#L578), but I don't remember why I decided to force the compilation error. I use `cxgo` for a pretty specific codebase, so I might have done it due to some issue there.

In any case, I agree that it should produce `_ = a` by default.
