### ISSUE TITLE
Question regarding defines 

### ISSUE THREAD

**Issue by g41797** [gotranspile/cxgo#62]
Before opening of NI , i send the same information to community (gotranspile/community room)
Looks not active since dec 2022

Because all examples failed on my computer (different reasons), I tried to check simple single file:

        #include <stdlib.h>
        #include <errno.h>
        void main() {
	        errno = ENOMEM;
        }

cxgo file main.c

creates :

    package main
    
    import "github.com/gotranspile/cxgo/runtime/libc"
    
    func main() {
	    libc.Errno = ENOMEM
    }

go build main.go returns error:

.**/main.go:6:15: undefined: ENOMEM**

I expected that RegisterLibrary("errno.h",... will replace ENOMEM or add const to go file

This problem was solved using replace:
      package: main
      int_size: 8
      ptr_size: 8
      use_go_int: true
      files:
      _name: main.c
      replace:
      old: 'ENOMEM'
      new: '50'_

What is the right way?

**Comment by dennwc** [comment]
> Before opening of NI , i send the same information to community (gotranspile/community room)
Looks not active since dec 2022

Hmm, weird, I see you messages on `gitter.im`, but it's not getting to my server for whatever reason. Will investigate.

> I expected that RegisterLibrary("errno.h",... will replace ENOMEM or add const to go file

Looking at the code, the `errno.h` currently only defines these constants on C side, but doesn't provide a Go mapping.

It's pretty straightforward to add, there's an `Idents` section in that `Register` call, which needs an entry for each error code. Definition can be copied from a mapping for `libc.Errno`.

Also, the `runtime/libc` needs all these constants added as well.

You can either file a PR with the changes, or use `replace` as you did until I fix it (hopefully later today).

**Comment by g41797** [comment]
yesterday i learned that PR is pull request 😞
so issue of "my" PR will take some days

anyway i am looking for go project to contribute so i have no problem to
start from simple fixes, new mapping, testing etc

some notes:

   - build of .examples/potrace-go failed with ./bitmap.go:49:16:
   undefined: ENOMEM
   - yaml file for potrace doesn't contain any map/replace
   - it was the reason to expect automatic processing via RegisterLibrary
   because defines were embedded to source

**Comment by dennwc** [comment]
> yesterday i learned that PR is pull request disappointed
> so issue of "my" PR will take some days

No worries, you may actually be faster than I am in this case :sweat_smile: 

> anyway i am looking for go project to contribute so i have no problem to
> start from simple fixes, new mapping, testing etc

That would be a good starting point indeed!

>  build of .examples/potrace-go

You are building the one from examples, right? I made a new conversion some time ago, it's configured a bit better: https://github.com/gotranspile/gotrace.

**Comment by g41797** [comment]
For the case of ENOMEM panic is OK

The real problem is a lot of manual work for the mapping of defines to const

Actually for the current source cxgo does it, but for defines in includes doesn't

I understand that defining of the same const name e.g. ENOMEM
within different sources in the package is wrong 
But 'ENOMEM+source name' name of the const may solve the problem
Or automatically create defines.go file with all used consts 

I am talking about simple defines (with clear "type")
What does cxgo "know" about define?

For now let's leave all fantasies above aside
How can I help ?

**Comment by g41797** [comment]
please add hints 
i am going to continue

**Comment by dennwc** [comment]
Here's the things that need to be done for each constant:

1. Rewrite the C header in `errno.go` to replace `#define` with `const int`, for example: `#define EACCES 3` -> `const int EACCES = 3;`
2. Make a Go mapping for it in `Idents`, similar to how `errno` is defined, e.g. `"EACCES": c.NewIdent("EACCES", "libc.EACCES", libc.EACCES, gint),`.
3. The line above will fail to compile, because you'll also need to define this const in `runtime/libc/errno.go`: `const EACCES = 3`.

This should be enough to generate proper code for these constants. It can be automated a bit with a loop in `RegisterLibrary` callback.

**Comment by g41797** [comment]
Fixed
see #67
